# Generated by Django 3.1.4 on 2020-12-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('made_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=200, unique=True, verbose_name='Nom')),
                ('last_name', models.CharField(max_length=200, unique=True, verbose_name='Prénoms')),
                ('agency_name', models.CharField(max_length=200, unique=True, verbose_name="Nom de l'agence")),
                ('cities', models.CharField(choices=[('ABOBO', 'Abobo'), ('ADJAME', 'Adjamé'), ('ATTECOUBE', 'Attécoubé'), ('COCOCDY', 'Cocody'), ('KOUMASSI', 'Koumassi'), ('MARCORY', 'Marcory'), ('PLATEAU', 'Plateau'), ('PORT-BOUET', 'Port-Boùet'), ('TREICHVILLE', 'Treichville'), ('YOPOUGON', 'Yopougon')], max_length=200, verbose_name='Commune')),
                ('categories', models.CharField(choices=[('VILLA', 'Villa'), ('APPARTEMENT', 'Appartement'), ('HAUT-STANDING', 'Haut-standing'), ('DUPLEX', 'Duplex'), ('COUR', 'Cour'), ('2 PIECES', '2 pièces'), ('3 PIECES', '3 pièces')], max_length=200, verbose_name='Catégories')),
                ('status', models.CharField(choices=[('VENTE', 'Vente'), ('LOCATION', 'Location')], max_length=200, verbose_name='Statut')),
                ('number_1', models.CharField(max_length=200, unique=True, verbose_name='Contact 1')),
                ('number_2', models.CharField(blank=True, max_length=200, unique=True, verbose_name='Contact 2')),
                ('description', models.TextField(max_length=1000, verbose_name='Description')),
                ('image_one', models.ImageField(upload_to='img_upload', verbose_name='Image')),
            ],
        ),
    ]
