# Generated by Django 3.1.4 on 2020-12-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='image_one',
            field=models.ImageField(upload_to='img_upload/', verbose_name='Image'),
        ),
    ]
