# Generated by Django 3.1.4 on 2020-12-04 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0002_auto_20201204_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='number_1',
            field=models.IntegerField(max_length=200, unique=True, verbose_name='Contact 1'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='number_2',
            field=models.IntegerField(blank=True, max_length=200, unique=True, verbose_name='Contact 2'),
        ),
    ]
