# Generated by Django 3.1.4 on 2020-12-04 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0003_auto_20201204_0321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='number_1',
            field=models.IntegerField(unique=True, verbose_name='Contact 1'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='number_2',
            field=models.IntegerField(blank=True, unique=True, verbose_name='Contact 2'),
        ),
    ]
