# Generated by Django 3.1.4 on 2020-12-16 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0004_auto_20201204_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='agency_name',
            field=models.CharField(max_length=200, verbose_name="Nom de l'agence"),
        ),
        migrations.AlterField(
            model_name='publication',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='image_one',
            field=models.FileField(upload_to='img_upload/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='Prénoms'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='number_1',
            field=models.IntegerField(verbose_name='Contact 1'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='number_2',
            field=models.IntegerField(null=True, verbose_name='Contact 2'),
        ),
    ]
