# Generated by Django 3.1.4 on 2020-12-16 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub', '0005_auto_20201216_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='categories',
            field=models.CharField(choices=[('VILLA', 'Villa'), ('APPARTEMENT', 'Appartement'), ('HAUT-STANDING', 'Haut-standing'), ('DUPLEX', 'Duplex'), ('COUR', 'Cour'), ('2 PIECES', '2 pièces'), ('3 PIECES', '3 pièces')], max_length=200, unique=True, verbose_name='Catégories'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='cities',
            field=models.CharField(choices=[('ABOBO', 'Abobo'), ('ADJAME', 'Adjamé'), ('ATTECOUBE', 'Attécoubé'), ('COCOCDY', 'Cocody'), ('KOUMASSI', 'Koumassi'), ('MARCORY', 'Marcory'), ('PLATEAU', 'Plateau'), ('PORT-BOUET', 'Port-Boùet'), ('TREICHVILLE', 'Treichville'), ('YOPOUGON', 'Yopougon')], max_length=200, unique=True, verbose_name='Commune'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='status',
            field=models.CharField(choices=[('VENTE', 'Vente'), ('LOCATION', 'Location')], max_length=200, unique=True, verbose_name='Statut'),
        ),
    ]
